### PR TITLE
Suggesting a fuller README template

### PR DESCRIPTION
**Pull request by Perlkonig**
Just a suggestion. Feedback warmly welcomed. 

* I used `set` statements to avoid twig running the same filter a hundred times.

* This does *not* include the `feature/githubid` branch (PR #5). Should you choose to incorporate that branch as well, then I would change line three of the twig file to `{% set uHyphen = (component.author.githubid|hyphenize) %}`.

### CODE REVIEW

**Comment by Vivalldi** [comment]
Just out of curiosity, any reason you are prefixing with `c` and `u`?

**Comment by Perlkonig** [comment]
I can fix those. Clearly I'm in haste. C = component, u = user (developer). 
I'll fix that when I'm back a little later this afternoon.

Sorry.

**Comment by Perlkonig** [comment]
Fixed. Sorry. That was sloppy of me.

**Comment by Vivalldi** [comment]
Thanks! I'll look at #5 when I get a chance

**Pull request merged**
